name: Build and push dockers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PREPROD_UTXORPC_API_KEY: ${{secrets.PREPROD_UTXORPC_API_KEY}}
      PREPROD_UTXORPC_URL: ${{secrets.PREPROD_UTXORPC_URL}}
      PREPROD_BLOCKFROST_URL: ${{secrets.PREPROD_BLOCKFROST_URL}}
      PREPROD_BLOCKFROST_API_KEY: ${{secrets.PREPROD_BLOCKFROST_API_KEY}}
      PREPROD_DB_SYNC_CONNECTION_STRING: ${{secrets.PREPROD_DB_SYNC_CONNECTION_STRING}}
      PREVIEW_UTXORPC_API_KEY: ${{secrets.PREVIEW_UTXORPC_API_KEY}}
      PREVIEW_UTXORPC_URL: ${{secrets.PREVIEW_UTXORPC_URL}}
      PREVIEW_BLOCKFROST_URL: ${{secrets.PREVIEW_BLOCKFROST_URL}}
      PREVIEW_BLOCKFROST_API_KEY: ${{secrets.PREVIEW_BLOCKFROST_API_KEY}}
      PREVIEW_DB_SYNC_CONNECTION_STRING: ${{secrets.PREVIEW_DB_SYNC_CONNECTION_STRING}}
      MAINNET_UTXORPC_API_KEY: ${{secrets.MAINNET_UTXORPC_API_KEY}}
      MAINNET_UTXORPC_URL: ${{secrets.MAINNET_UTXORPC_URL}}
      MAINNET_BLOCKFROST_URL: ${{secrets.MAINNET_BLOCKFROST_URL}}
      MAINNET_BLOCKFROST_API_KEY: ${{secrets.MAINNET_BLOCKFROST_API_KEY}}
      MAINNET_DB_SYNC_CONNECTION_STRING: ${{secrets.MAINNET_DB_SYNC_CONNECTION_STRING}}
      AF_VECTOR_TESTNET_UTXORPC_API_KEY: ${{secrets.AF_VECTOR_TESTNET_UTXORPC_API_KEY}}
      AF_VECTOR_TESTNET_UTXORPC_URL: ${{secrets.AF_VECTOR_TESTNET_UTXORPC_URL}}
      AF_VECTOR_TESTNET_BLOCKFROST_URL: ${{secrets.AF_VECTOR_TESTNET_BLOCKFROST_URL}}
      AF_VECTOR_TESTNET_BLOCKFROST_API_KEY: ${{secrets.AF_VECTOR_TESTNET_BLOCKFROST_API_KEY}}
      AF_VECTOR_TESTNET_DB_SYNC_CONNECTION_STRING: ${{secrets.AF_VECTOR_TESTNET_DB_SYNC_CONNECTION_STRING}}
      AF_VECTOR_MAINNET_UTXORPC_API_KEY: ${{secrets.AF_VECTOR_MAINNET_UTXORPC_API_KEY}}
      AF_VECTOR_MAINNET_UTXORPC_URL: ${{secrets.AF_VECTOR_MAINNET_UTXORPC_URL}}
      AF_VECTOR_MAINNET_BLOCKFROST_URL: ${{secrets.AF_VECTOR_MAINNET_BLOCKFROST_URL}}
      AF_VECTOR_MAINNET_BLOCKFROST_API_KEY: ${{secrets.AF_VECTOR_MAINNET_BLOCKFROST_API_KEY}}
      AF_VECTOR_MAINNET_DB_SYNC_CONNECTION_STRING: ${{secrets.AF_VECTOR_MAINNET_DB_SYNC_CONNECTION_STRING}}
      AF_PRIME_TESTNET_UTXORPC_API_KEY: ${{secrets.AF_PRIME_TESTNET_UTXORPC_API_KEY}}
      AF_PRIME_TESTNET_UTXORPC_URL: ${{secrets.AF_PRIME_TESTNET_UTXORPC_URL}}
      AF_PRIME_TESTNET_BLOCKFROST_URL: ${{secrets.AF_PRIME_TESTNET_BLOCKFROST_URL}}
      AF_PRIME_TESTNET_BLOCKFROST_API_KEY: ${{secrets.AF_PRIME_TESTNET_BLOCKFROST_API_KEY}}
      AF_PRIME_TESTNET_DB_SYNC_CONNECTION_STRING: ${{secrets.AF_PRIME_TESTNET_DB_SYNC_CONNECTION_STRING}}
      AF_PRIME_MAINNET_UTXORPC_API_KEY: ${{secrets.AF_PRIME_MAINNET_UTXORPC_API_KEY}}
      AF_PRIME_MAINNET_UTXORPC_URL: ${{secrets.AF_PRIME_MAINNET_UTXORPC_URL}}
      AF_PRIME_MAINNET_BLOCKFROST_URL: ${{secrets.AF_PRIME_MAINNET_BLOCKFROST_URL}}
      AF_PRIME_MAINNET_BLOCKFROST_API_KEY: ${{secrets.AF_PRIME_MAINNET_BLOCKFROST_API_KEY}}
      AF_PRIME_MAINNET_DB_SYNC_CONNECTION_STRING: ${{secrets.AF_PRIME_MAINNET_DB_SYNC_CONNECTION_STRING}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit hash
        run: echo "COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -f Dockerfile \
            $(env | grep -E 'PREPROD_UTXORPC_API_KEY|PREPROD_UTXORPC_URL|PREPROD_BLOCKFROST_URL|PREPROD_BLOCKFROST_API_KEY|PREPROD_DB_SYNC_CONNECTION_STRING|PREVIEW_UTXORPC_API_KEY|PREVIEW_UTXORPC_URL|PREVIEW_BLOCKFROST_URL|PREVIEW_BLOCKFROST_API_KEY|PREVIEW_DB_SYNC_CONNECTION_STRING|MAINNET_UTXORPC_API_KEY|MAINNET_UTXORPC_URL|MAINNET_BLOCKFROST_URL|MAINNET_BLOCKFROST_API_KEY|MAINNET_DB_SYNC_CONNECTION_STRING|AF_VECTOR_TESTNET_UTXORPC_API_KEY|AF_VECTOR_TESTNET_UTXORPC_URL|AF_VECTOR_TESTNET_BLOCKFROST_URL|AF_VECTOR_TESTNET_BLOCKFROST_API_KEY|AF_VECTOR_TESTNET_DB_SYNC_CONNECTION_STRING|AF_VECTOR_MAINNET_UTXORPC_API_KEY|AF_VECTOR_MAINNET_UTXORPC_URL|AF_VECTOR_MAINNET_BLOCKFROST_URL|AF_VECTOR_MAINNET_BLOCKFROST_API_KEY|AF_VECTOR_MAINNET_DB_SYNC_CONNECTION_STRING|AF_PRIME_TESTNET_UTXORPC_API_KEY|AF_PRIME_TESTNET_UTXORPC_URL|AF_PRIME_TESTNET_BLOCKFROST_URL|AF_PRIME_TESTNET_BLOCKFROST_API_KEY|AF_PRIME_TESTNET_DB_SYNC_CONNECTION_STRING|AF_PRIME_MAINNET_UTXORPC_API_KEY|AF_PRIME_MAINNET_UTXORPC_URL|AF_PRIME_MAINNET_BLOCKFROST_URL|AF_PRIME_MAINNET_BLOCKFROST_API_KEY|AF_PRIME_MAINNET_DB_SYNC_CONNECTION_STRING' | sed 's/^/--build-arg /' | tr '\n' ' ') \
            -t nicolasluduena/utxo-explorer:ui-${COMMIT_HASH} \
            -t nicolasluduena/utxo-explorer:ui-${{ github.ref_name }} . \
            --progress=plain

      - name: Push Docker Image to Docker Hub
        run: |
          docker push nicolasluduena/utxo-explorer:ui-${COMMIT_HASH}      
          docker push nicolasluduena/utxo-explorer:ui-${{ github.ref_name }} .

      - name: Redeploy service in coolify
        run: |
          echo "Deploying UUID: ${{ vars.COOLIFY_SERVICE_UUID }}"
          curl -X POST "https://${{ vars.COOLIFY_BASE_URL }}/api/v1/deploy?uuid=${{ vars.COOLIFY_SERVICE_UUID }}&force=false" \
            -H "Authorization: Bearer ${{secrets.COOLIFY_API_TOKEN}}" \
            -H "Content-Type: application/json"
